{% macro expected__class_desc(type) %}
{%- set var = 'class_desc' -%}
{%- if type == 'raw' -%}
    {{ __raw_class_desc() }}
{%- elif type == 'clean' -%}
    {{ __clean_class_desc() }}
{%- else -%}
    'Error: Invalid type provided to expected__{{ var }} macro'
{%- endif -%}
{% endmacro %}

{%- macro __raw_class_desc() -%}
    [
        'Accounting Services',
        'Actuarial Services',
        'Acupuncturist (Licensed MD)',
        'Acupuncturist (non-MD)',
        'Administrative Office Services',
        'Advertising Agencies',
        'Advertising Consulting Services',
        'Aerobic Dance & Exercise Centers',
        'Air Conditioning Systems & Equipment - Distribution Only',
        'Allergist',
        'Anesthesiologist',
        'Appliance Rental',
        'Appliance Stores',
        'Appliances & Accessories - Installation, Service or Repair - Commercial',
        'Appliances & Accessories - Installation, Service or Repair - Household',
        'Appliances & Accessories - Service or Repair - In Shop/Store',
        'Appraisal Services (other than Real Estate Appraisal)',
        'Arbitration & Mediation Services',
        'Art Galleries',
        'Art Studios & Services',
        'Art Supply Stores',
        'Art Therapist',
        'Artificial Flower & Supplies Wholesalers',
        'Athletic Apparel Stores',
        'Athletic Equipment Stores',
        'Audiologist',
        'Auditing Services',
        'Automotive Glass Repair & Replacement',
        'Awning Wholesalers',
        'Bagel & Baked Goods Cafes',
        'Bakeries - Baking on Premises - No Onsite Consumption',
        'Bakeries - No Baking on Premises - No Onsite Consumption',
        'Barber Shops',
        'Bath & Bedding Wholesalers',
        'Bath, Bedding & Kitchen Shops',
        'Beauty & Barber Shop Equipment & Supply Wholesalers',
        'Beauty Parlors',
        'Beverage Bars (Juice, Smoothies, Coffee) - No Alcohol',
        'Beverage Stores - Non Alcoholic',
        'Beverage Wholesalers - Non Alcoholic',
        'Bicycle Shops',
        'Bicycles & other Sporting Goods Repair & Maintenance',
        'Billing Services',
        'Book & Magazine Stores',
        'Book & Magazine Wholesalers',
        'Book Binding & Printing Supply Wholesalers',
        'Bookkeeping',
        'Bridal Wear Rental',
        'Business Management Consulting NOC',
        'Cabinet Stores - No Installation',
        'Cabinet Wholesalers',
        'Calendar Stores',
        'Camera Repair',
        'Camera Shops',
        'Candle Shops',
        'Candle Wholesalers',
        'Candy, Confectionary & Nut Stores - Manufacturing on Premises',
        'Candy, Confectionary & Nut Stores - No Manufacturing on Premises',
        'Canned Food Wholesalers',
        'Card & Stationery Stores',
        'Card, Stationery or Paper Products Wholesalers',
        'Cardiologists',
        'Carpet, Rug, Furniture or Upholstery Cleaning - On Customers Premises',
        'Caterers',
        'Cell Phone Stores',
        'Cellular Telephone Wholesalers',
        'Cheese Shops',
        'Children & Infant Clothing Stores',
        'China, Ceramic, Glassware & Pottery Stores',
        'Chiropractor',
        'Christmas Ornament Wholesalers',
        'Christmas Stores',
        'Cleaning Services - Curtain and Drapery - No Plant on Premises',
        'Closet Organizer System Installation',
        'Clothing & Apparel Stores - NOC',
        'Clothing & Apparel Wholesalers - NOC',
        'Clothing Rental - NOC',
        'Coffee & Tea Stores - No Consumption on Premises',
        'Coffee & Tea Supplies Wholesalers',
        'Coffee Bars or Cafés',
        'Collectibles & Memorabilia Stores',
        'Collection Agencies - No Repossession Services',
        'Commercial Art & Graphic Design',
        'Commercial Condominiums & Cooperatives - Other than Offices - Association Risk Only',
        'Compensation & Benefits Consulting',
        'Computer Equipment & Software Stores',
        'Computer Equipment Repair - in Shop/Store',
        'Computer Rental',
        'Computers, Radio, TV or Sound Equipment Wholesalers',
        'Concession & Refreshment Stands - No Alcohol & Limited Cooking',
        'Conferencing Services',
        'Consumer Credit Counseling',
        'Convenience Stores - No Gas Sales or Restaurant',
        'Copying & Duplicating Services',
        'Cosmetic, Beauty Supplies & Perfume Stores',
        'Costume Design',
        'Costume Rental',
        'Costume Stores',
        'Court Reporting & Stenography Services',
        'Dairy Stores',
        'Day Spas',
        'Delicatessen & Sandwich Shops',
        'Delicatessens - No Onsite Consumption',
        'Department Stores',
        'Dermatologist',
        'Diaper, Uniform & Linen Supply Rental',
        'Dietician or Nutritionist',
        'Direct Mail Advertising Service',
        'Disc Jockey',
        'Discount Stores',
        'Document Preparation Services',
        'Dollar Stores',
        'Donut Shops - No Frying on Premises',
        'Draftsmen & Blueprint Services',
        'Education & School Supply Wholesalers',
        'Electronic Equipment Rental',
        'Electronic Game Wholesalers',
        'Electronics Repair - in Shop/Store',
        'Electronics Stores',
        'Emergency Preparedness Supply Stores',
        'Employment Agencies',
        'Equestrian Supply Stores',
        'Event Planning',
        'Executive Recruiters',
        'Fabric Stores',
        'Fabric Wholesalers',
        'Family Clothing Stores',
        'Fashion & Jewelry Design',
        'Fence Stores or Dealers',
        'Fence Wholesalers',
        'Financial Management Consulting',
        'Financial Planning & Investment Advice',
        'Fish or Seafood Stores - No Cooking on Premises',
        'Flag & Banner Shops',
        'Floor Covering Distributors',
        'Floor Covering, Carpet & Tile Store',
        'Florists',
        'Footwear Repair',
        'Fresh Flowers & Supplies Wholesalers',
        'Fruit & Vegetable Markets',
        'Funeral Services',
        'Furniture Stores',
        'Furniture Wholesalers',
        'Garden Centers',
        'Gardening & Light Farming Supply Wholesalers',
        'Gastroenterologist',
        'General Practitioner',
        'Gift Shops',
        'Glass Dealers & Glaziers - No Installation',
        'Grocery Stores - At least 4,000 sq. ft; No Gasoline Sales',
        'Grocery Stores - Less than 4,000 sq. ft; No Gasoline Sales',
        'Gynecologist',
        'HVAC equipment - Distributors Only',
        'Hair Styling Salons',
        'Hardware & Tools Distributors',
        'Hardware Stores',
        'Hat & Cap Stores',
        'Health & Natural Food Stores',
        'Hearing Aid Stores',
        'Hobby or Craft Supply Distributors',
        'Hobby or Craft Supply Stores',
        'Home Improvement Stores',
        'Home Security Equipment Stores',
        'Homeowners Associations - Association Risk Only',
        'Hosiery & Lingerie Stores',
        'Housekeeping & Cleaning Services',
        'Human Resources Consulting',
        'Ice Cream & Frozen Yogurt Shops or Stands',
        'Ice Cream Stores - No Consumption on Premises',
        'Immunologist',
        'Income Tax Services',
        'Insurance Agents & Brokers',
        'Insurance Claim Handling Services',
        'Insurance Consulting & Reporting Services',
        'Insurance Inspection & Appraisal Services (No Claims)',
        'Interior Decorating & Design',
        'Internist',
        'Interpretation & Translation',
        'Janitorial Supplies Stores',
        'Janitorial Supply Wholesalers',
        'Jewelry - Costume - Wholesalers',
        'Jewelry Box Wholesalers',
        'Jewelry Repair',
        'Jewelry Stores - Costume',
        'Jury & Trial Consulting',
        'Kitchen Equipment & Accessory Wholesalers',
        'Lamps & Lighting Fixtures Wholesalers',
        'Landscape Care & Maintenance Services',
        'Language & Interpretation Services',
        'Large Household Appliance Wholesalers',
        'Laundry & Dry Cleaning Receiving Station - No Plant On Premises',
        'Lawyers',
        'Leather Clothing Stores',
        'Leather Good Stores - other than apparel',
        'Lessors Risk - Office Occupancy Only',
        'Lessors Risk - Retail or Service Occupancy',
        'Lessors Risk - Wholesale or Distribution Occupancy',
        'Life Coach Services',
        'Lighting Stores',
        'Locksmith & Key Cutting',
        'Luggage Goods',
        'Luggage Wholesalers',
        'Mail or Packaging Stores & Services',
        'Manufacturers Representatives - Food & Non-Alcoholic Beverage Products',
        'Manufacturers Representatives - NOC',
        'Manufacturing or Logistics Consulting',
        'Marketing Analysis Firms or Agencies',
        'Marketing Research Services',
        'Massage Therapist',
        'Maternity Stores',
        'Mattress Stores',
        'Meat or Poultry Stores - No Cooking on Premises',
        'Medical Spas',
        'Medical, Hospital or Surgical Supply Stores',
        'Mens & Boys Clothing Stores',
        'Mens & Boys Clothing Wholesalers',
        'Mental Health Doctors',
        'Missing',
        'Monument & Tombstone Wholesalers',
        'Mortgage Broker',
        'Music Stores - Pre-Recorded Records & Compact Discs',
        'Music Therapist',
        'Musical Equipment Repair',
        'Musical Instrument Stores',
        'Musical Instrument Wholesalers',
        'Nail Salons',
        'Neurologist',
        'Neuropathologist',
        'Notary Publics',
        'Novelty Article Wholesalers',
        'Obstetrician',
        'Occupational Therapist',
        'Office & School Supply Stores',
        'Office & Store Equipment Wholesalers',
        'Office Condominium & Cooperative Associations - Association Risk Only',
        'Office Equipment Rental',
        'Office Furniture Stores',
        'Office Machine Repair',
        'Office Machine or Appliance Stores',
        'Office Machine or Appliance Wholesalers - No Repair',
        'Office Supplies Wholesalers',
        'Office Supply Stores',
        'Oncologist',
        'Optical Goods Distributors',
        'Optical Goods Stores',
        'Orthopedic & Specialty Shoe Stores',
        'Orthopedic Surgeon',
        'Osteopathic Physician',
        'Otolaryngologist',
        'Paint, Wallpaper or Wallcovering Stores',
        'Paint, Wallpaper, & Wallcoverings Wholesalers',
        'Paper Bag, Box, Container Wholesalers',
        'Paper Goods Wholesalers - NOC',
        'Paralegal Services',
        'Party Equipment Rental - Tables, Chairs, Dishes - No Amusement Devices',
        'Party Goods Stores',
        'Patent Agent & Broker Services',
        'Pathologist',
        'Payroll Accounting Services',
        'Personal Assistant Services',
        'Pet & Pet Supplies Stores',
        'Pet Boarding',
        'Pet Grooming',
        'Pet Sitting',
        'Pet Supply Wholesalers',
        'Pet Training',
        'Photographers',
        'Photographic Equipment Stores',
        'Physicians Assistant',
        'Picture & Picture Frame Shops',
        'Picture Frame Wholesalers',
        'Plumbing Supplies & Fixtures Stores',
        'Plumbing Supplies & Fixtures Wholesalers',
        'Podiatrist',
        'Pottery Painting Stores',
        'Precision & Scientific Tools & Instrument Stores',
        'Psychiatrist',
        'Psychoanalyst (other than MD or DO)',
        'Psychologist',
        'Psychotherapist (MD or DO)',
        'Psychotherapist (other than MD or DO)',
        'Public Opinion & Rating Services',
        'Public Relations Services',
        'Publishers - no printing, office only',
        'Pulmonary Specialist',
        'Purse Stores',
        'Quick Print & Copy Store',
        'Radio, TV or Sound Equipment Stores',
        'Radiologist',
        'Real Estate Agents & Brokers',
        'Real Estate Appraisal Services',
        'Real Estate Listing Services',
        'Real Estate Title & Settlement Services',
        'Recording Studio',
        'Refrigeration Equipment Distributors - Commercial Use',
        'Religious Materials Stores',
        'Religious Materials Wholesalers',
        'Restaurant, Bars & Hotel Equipment Distributors',
        'Sales & Marketing Consulting',
        'Sewing Machine Stores',
        'Shoe Stores',
        'Shoe Wholesalers',
        'Shopping Bags Wholesalers - Paper & Plastics',
        'Shopping Center',
        'Siding Dealers - No Installation',
        'Sign Lettering & Painting - no exterior work; no spray painting',
        'Sign Wholesalers',
        'Sleep Center',
        'Small Household Appliance Wholesalers',
        'Sock Stores',
        'Speakers, Announcers & Commentators',
        'Specialty Food Stores',
        'Speech Pathologist',
        'Spice Stores',
        'Spinning Studios',
        'Sporting Goods Stores',
        'Sportswear Wholesalers',
        'Statue Wholesalers',
        'Stock Brokers',
        'Store Staging or Decorating',
        'Strategic Planning Consulting',
        'Sunglass Stores',
        'Supermarkets - At least 4,000 sq. ft; No Gasoline Sales',
        'Supermarkets - less than 4,000 sq. ft; No Gasoline Sales',
        'Surgeon',
        'Surveying Services',
        'Swimming Pool Supply Stores - No Pool Installation',
        'Tackle Shops (including Bait)',
        'Tailors or Dressmakers',
        'Taxidermists',
        'Technology Consulting - Hardware & Software',
        'Ticket Agencies - Other Than Theatrical',
        'Ticket Agencies - Theatrical',
        'Tire Dealers - No Installation',
        'Toy Stores',
        'Travel Reservation Services - No tour operations',
        'Trophy Shops',
        'Trophy Wholesalers',
        'Uniform Stores',
        'Urologist',
        'Video & Video Game Stores including Rental',
        'Videographers',
        'Watch & Clock Repair',
        'Wig Stores',
        'Window & Door Stores - No Installation',
        'Window Cleaning Services',
        'Window Shade, Blind & Fixture Stores - No Installation',
        'Window Treatment Installation',
        'Womens & Girls Clothing Stores',
        'Writer - Independent or Freelance',
        'Yoga & Pilates Centers'
    ]
{%- endmacro -%}

{%- macro __clean_class_desc() -%}
    {{ __raw_class_desc() }}
{%- endmacro -%}