{% macro expected__business_segment(type) %}
{%- set var = 'business_segment' -%}
{%- if type == 'raw' -%}
    [
        'Accommodation',
        'Administration of Housing Programs, Urban Planning, and Community Development',
        'Administrative and Support Services',
        'Ambulatory Health Care Services',
        'Amusement, Gambling, and Recreation Industries',
        'Animal Production and Aquaculture',
        'Apparel Manufacturing',
        'Beverage and Tobacco Product Manufacturing',
        'Broadcasting (except Internet)',
        'Building Material and Garden Equipment and Supplies Dealers',
        'Chemical Manufacturing',
        'Clothing and Clothing Accessories Stores',
        'Computer and Electronic Product Manufacturing',
        'Construction of Buildings',
        'Couriers and Messengers',
        'Credit Intermediation and Related Activities',
        'Crop Production',
        'Data Processing, Hosting, and Related Services',
        'Educational Services',
        'Electronics and Appliance Stores',
        'Executive, Legislative, and Other General Government Support',
        'Fabricated Metal Product Manufacturing',
        'Food Manufacturing',
        'Food Services and Drinking Places',
        'Food and Beverage Stores',
        'Funds, Trusts, and Other Financial Vehicles',
        'Furniture and Home Furnishings Stores',
        'Furniture and Related Product Manufacturing',
        'Gasoline Stations',
        'General Merchandise Stores',
        'Health and Personal Care Stores',
        'Heavy and Civil Engineering Construction',
        'Hospitals',
        'Insurance Carriers and Related Activities',
        'Justice, Public Order, and Safety Activities',
        'Machinery Manufacturing',
        'Management of Companies and Enterprises',
        'Merchant Wholesalers, Durable Goods',
        'Merchant Wholesalers, Nondurable Goods',
        'Mining (except Oil and Gas)',
        'Miscellaneous Manufacturing',
        'Miscellaneous Store Retailers',
        'issing',
        'Motion Picture and Sound Recording Industries',
        'Motor Vehicle and Parts Dealers',
        'Museums, Historical Sites, and Similar Institutions',
        'Nonmetallic Mineral Product Manufacturing',
        'Nonstore Retailers',
        'Nursing and Residential Care Facilities',
        'Oil and Gas Extraction',
        'Other Information Services',
        'Performing Arts, Spectator Sports, and Related Industries',
        'Personal and Laundry Services',
        'Plastics and Rubber Products Manufacturing',
        'Printing and Related Support Activities',
        'Private Households',
        'Professional, Scientific, and Technical Services',
        'Publishing Industries (except Internet)',
        'Real Estate',
        'Religious, Grantmaking, Civic, Professional, and Similar Organizations',
        'Rental and Leasing Services',
        'Repair and Maintenance',
        'Securities, Commodity Contracts, and Other Financial Investments and Related Activities',
        'Social Assistance',
        'Specialty Trade Contractors',
        'Sporting Goods, Hobby, Musical Instrument, and Book Stores',
        'Support Activities for Agriculture and Forestry',
        'Support Activities for Mining',
        'Support Activities for Transportation',
        'Telecommunications',
        'Transit and Ground Passenger Transportation',
        'Truck Transportation',
        'Utilities',
        'Warehousing and Storage',
        'Wholesale Electronic Markets and Agents and Brokers',
        'Wood Product Manufacturing'
    ]
{%- elif type == 'clean' -%}
    [
        'Accommodation',
        'Administration of Housing Programs, Urban Planning, and Community Development',
        'Administrative and Support Services',
        'Ambulatory Health Care Services',
        'Amusement, Gambling, and Recreation Industries',
        'Animal Production and Aquaculture',
        'Apparel Manufacturing',
        'Beverage and Tobacco Product Manufacturing',
        'Broadcasting (except Internet)',
        'Building Material and Garden Equipment and Supplies Dealers',
        'Chemical Manufacturing',
        'Clothing and Clothing Accessories Stores',
        'Computer and Electronic Product Manufacturing',
        'Construction of Buildings',
        'Couriers and Messengers',
        'Credit Intermediation and Related Activities',
        'Crop Production',
        'Data Processing, Hosting, and Related Services',
        'Educational Services',
        'Electronics and Appliance Stores',
        'Executive, Legislative, and Other General Government Support',
        'Fabricated Metal Product Manufacturing',
        'Food Manufacturing',
        'Food Services and Drinking Places',
        'Food and Beverage Stores',
        'Funds, Trusts, and Other Financial Vehicles',
        'Furniture and Home Furnishings Stores',
        'Furniture and Related Product Manufacturing',
        'Gasoline Stations',
        'General Merchandise Stores',
        'Health and Personal Care Stores',
        'Heavy and Civil Engineering Construction',
        'Hospitals',
        'Insurance Carriers and Related Activities',
        'Justice, Public Order, and Safety Activities',
        'Machinery Manufacturing',
        'Management of Companies and Enterprises',
        'Merchant Wholesalers, Durable Goods',
        'Merchant Wholesalers, Nondurable Goods',
        'Mining (except Oil and Gas)',
        'Miscellaneous Manufacturing',
        'Miscellaneous Store Retailers',
        'issing',
        'Motion Picture and Sound Recording Industries',
        'Motor Vehicle and Parts Dealers',
        'Museums, Historical Sites, and Similar Institutions',
        'Nonmetallic Mineral Product Manufacturing',
        'Nonstore Retailers',
        'Nursing and Residential Care Facilities',
        'Oil and Gas Extraction',
        'Other Information Services',
        'Performing Arts, Spectator Sports, and Related Industries',
        'Personal and Laundry Services',
        'Plastics and Rubber Products Manufacturing',
        'Printing and Related Support Activities',
        'Private Households',
        'Professional, Scientific, and Technical Services',
        'Publishing Industries (except Internet)',
        'Real Estate',
        'Religious, Grantmaking, Civic, Professional, and Similar Organizations',
        'Rental and Leasing Services',
        'Repair and Maintenance',
        'Securities, Commodity Contracts, and Other Financial Investments and Related Activities',
        'Social Assistance',
        'Specialty Trade Contractors',
        'Sporting Goods, Hobby, Musical Instrument, and Book Stores',
        'Support Activities for Agriculture and Forestry',
        'Support Activities for Mining',
        'Support Activities for Transportation',
        'Telecommunications',
        'Transit and Ground Passenger Transportation',
        'Truck Transportation',
        'Utilities',
        'Warehousing and Storage',
        'Wholesale Electronic Markets and Agents and Brokers',
        'Wood Product Manufacturing'
    ]
{%- else -%}
    'Error: Invalid type provided to expected__{{ var }} macro'
{%- endif -%}
{% endmacro %}
