{%- macro mosum_columns__select() -%}

{%- set prepend = "mosum__" -%}
{%- set mosum_cols = [
    "mo_sum_sk",
    "agency_zip_code",
    "is_building_only",
    "contractor_group",
    "company_state_code",
    "completed_ops_group",
    "is_composite_rated",
    "emp_size_code",
    "experian_bin",
    "experian_naics",
    "lob_code",
    "naics",
    "is_new_package",
    "is_package",
    "policy_id",
    "policy_state",
    "has_premops",
    "prevailing_fire_protection_class",
    "prevailing_policy_type",
    "prevailing_state",
    "risk_type",
    "state_codes",
    "agency_total_premium",
    "agency_total_volume",
    "n_all_trades",
    "amount_of_insurance",
    "average_balance",
    "avg_building_size",
    "bad_trade_ratio",
    "balance_90",
    "balance_regular_trade_lines",
    "total_balance",
    "commercial_intelliscore",
    "n_derogatory_uccs",
    "experience_rmf",
    "hazard_grade",
    "n_indeterminate_trades",
    "n_judgements",
    "late_ratio",
    "n_liens",
    "ebc_manual_premium_amount",
    "n_classes",
    "n_derogatory_legal_items",
    "n_locations",
    "n_years_in_file",
    "non_pay_cancel_count_prev1",
    "non_pay_cancel_count_prev2",
    "non_pay_cancel_count_prev3",
    "n_months_in_cincibill_prev1",
    "n_months_in_cincibill_prev2",
    "n_months_in_cincibill_prev3",
    "payment_count_prev1",
    "payment_count_prev2",
    "payment_count_prev3",
    "pct_agency_premium",
    "policy_age",
    "policy_prem",
    "prev_1yr_claim_count",
    "prev_2yr_claim_count",
    "prev_3yr_claim_count",
    "prev_4yr_claim_count",
    "prev_5yr_claim_count",
    "prev_1yr_loss_amount",
    "prev_2yr_loss_amount",
    "prev_3yr_loss_amount",
    "prev_4yr_loss_amount",
    "prev_5yr_loss_amount",
    "prev_1yr_premium",
    "prev_2yr_premium",
    "prev_3yr_premium",
    "prev_4yr_premium",
    "prev_5yr_premium",
    "prev_1yr_nb_claim_count",
    "prev_2yr_nb_claim_count",
    "prev_3yr_nb_claim_count",
    "has_fire_claim_last_3_years",
    "has_water_claim_last_3_years",
    "has_gl_claim_last_3_years",
    "prev_nb_premium_amount",
    "prevailing_contents_deductible",
    "prevailing_single_limit",
    "n_risk_units",
    "n_states",
    "total_3yr_claim_count_closed_no_payment",
    "total_5yr_claim_count",
    "total_gl_premium_ratio",
    "ucc_ratio",
    "year_hash",
    "n_zero_trades",
    "n_zips"
] -%}

{%- for col in mosum_cols -%}
    "{{ col }}" as "{{ prepend }}{{ col }}"{%- if not loop.last %},{% endif %}
{%- endfor -%}

{%- endmacro -%}
