name: 'bop_modeling_data'
version: '1.0.0'

profile: 'bop_modeling_db'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'
  - 'dbt_packages'

models:
  bop_modeling_data:
    +materialized: view
    +docs:
      show: true
    00_raw:
      +materialized: table
      +tags:
        - raw
    01_stg:
      +materialized: view
      +tags:
        - stg
    02_lkp:
      +materialized: table
      +tags:
        - lkp
    03_dim:
      +materialized: view
      +tags:
        - dim
    07_tmp:
      +materialized: table
      +schema: zz__tmp
      +docs:
        show: false
      +tags:
        - tmp

vars:
  raw_csv_loc: '/sas/data/project/EG/ActShared/SmallBusiness/Modeling/dat/raw_csv'
  decfile_loc: '/sas/data/project/EG/ActShared/SmallBusiness/DecisionSupportFile/Development/2025/20250228'
  policy_eff_date__min_yrmo: 200901

flags:
  send_anonymous_usage_stats: false
