name: 'bop_modeling_data'
version: '1.0.0'

profile: 'bop_modeling_data'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  bop_modeling_data:
    +raw:
      schema: raw

vars:
  raw_csv_loc: "/sas/data/project/EG/ActShared/SmallBusiness/Modeling/dat/raw_csv"

  raw_csvs:
    - "ca_aiv"
    - "cf_aiv"
    - "gl_aiv"
    - "dlf"
    - "experian_credit_vars__2_8"
    - "experian_credit_vars__5_2"


on-run-start:
  - "create schema if not exists raw;"
    
