name: 'bop_modeling_data'
version: '1.0.0'

profile: 'bop_modeling_db'

model-paths: ['models']
analysis-paths: ['analyses']
test-paths: ['tests']
seed-paths: ['seeds']
macro-paths: ['macros']
snapshot-paths: ['snapshots']

clean-targets:
  - 'target'

models:
  bop_modeling_data:
    +materialized: view
    +docs:
      show: true
    00_raw:
      +schema: raw
      +materialized: table
      +tags:
        - raw
    01_stg:
      +schema: stg
      +materialized: view
      +tags:
        - stg
    02_lkp:
      +schema: lkp
      +materialized: table
      +tags:
        - lkp
    03_fct:
      +schema: fct
      +materialized: view
      +tags:
        - fct
    04_mrt:
      +schema: mrt
      +materialized: table
      +tags:
        - dm
        - mrt
        - datamart

data_tests:
  +store_failures: true
  +schema: test_failures

vars:
  null_sentinel: -9
  raw_csv_loc: '/sas/data/project/EG/ActShared/SmallBusiness/Modeling/dat/raw_csv'
  decfile_loc: '/sas/data/project/EG/ActShared/SmallBusiness/DecisionSupportFile/Development/2025/20250228'
  policy_eff_date__min_yrmo: 200901
  'dbt_date:time_zone': 'America/New_York'
  experian_loc: '/sas/data/project/EG/ActShared/ModelCommon/V5.3'

flags:
  send_anonymous_usage_stats: false
