name: 'bop_modeling_data'
version: '1.0.0'

profile: 'bop_modeling_db'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  bop_modeling_data:
    +materialized: view
    00_raw:
      +materialized: table

vars:
  raw_csv_loc: "/sas/data/project/EG/ActShared/SmallBusiness/Modeling/dat/raw_csv"
  decfile_loc: "/sas/data/project/EG/ActShared/SmallBusiness/DecisionSupportFile/Development/2025/20250228"

flags:
  send_anonymous_usage_stats: false